GET http://localhost:3001/api/blogs

###

POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer 

{
    "title": "Pekan blogi nr.5",
    "author": "Pekka Laakso",
    "url": "https://example.com",
    "likes": 100
}

###

DELETE http://localhost:3001/api/blogs/6548afc1ef7a6cf9173e7f7d
Authorization: Bearer 
