POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpbmVuIiwiaWQiOiI2NTQ1ZTMwY2MwZWE1NjVmYzUzODk1NTEiLCJpYXQiOjE2OTkwODM5MDB9.bNRxrPVzhUmAtb3iLAIlmARh-gGMkXimye9CgeCn774


{
    "title": "Tosi hieno blogi",
    "author": "Matti Luukainen",
    "url": "https://example.com",
    "likes": 100
}
