POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Sample Blog",
    "author": "Jane Doe",
    "url": "https://example.com",
    "likes": 100,
    "userId": "6544be1d20cc0123c1231816"
}
